# Generated by Django 6.0.7 on 2026-08-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_alter_article_author_alter_newsletter_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'journalist'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_newsletters', to=settings.AUTH_USER_MODEL),
        ),
    ]
